name: "Build backend"

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v26

      - name: Building package
        run: nix build .#backend
